In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [32]:
root = os.path.abspath("./MyDrive/data-stduy/")

In [36]:
csv = os.path.join(root, "1.csv")
data = pd.read_csv(csv)
data

       주        인구  살인 비율
0   앨라배마   4779736    5.7
1   알래스카    710231    5.6
2   애리조나   6392017    4.7
3    아칸소   2915918    5.6
4  캘리포니아  37253956    4.4

In [59]:
def get_avg(datas):
  return sum(datas) / len(datas)

def get_cut_avg(datas, trim:int=1):
  datas = list(datas)
  datas.sort()
  return sum(datas[trim: -1*trim]) / (len(datas) - (trim * 2))

population = data["인구"]
avg = get_avg(population)
cut_avg = get_cut_avg(population)

In [110]:
def get_weighted_avg(datas, w):
  return sum(datas * w) / sum(w)

def get_cut_weighted_avg(datas, trim:int=1):
  datas.sort(key=lambda x: x[0] * x[1])
  return sum(list(map(lambda x: x[0] * x[1],datas[trim: -1*trim]))) / sum(list(map(lambda x: x[1],datas[trim: -1*trim])))

murder_rate = data["살인 비율"]
population = data["인구"]
get_weighted_avg(murder_rate, population)
get_cut_weighted_avg(data[["살인 비율", "인구"]].values.tolist(), 1)

5.225570351550657